-- ============================================================
-- SEED: GLOBAL FUNDINGS
-- 55 real funding programmes — grants, blended finance, equity
-- Every eligibility variable populated for matchmaking
-- ============================================================

-- Helper: grab provider IDs inline
WITH p AS (SELECT id, short_name FROM public.capital_providers)
INSERT INTO public.capital_fundings (
  provider_id, program_name, funding_type,
  amount_min_usd, amount_max_usd, currency, total_envelope_usd,
  eligible_regions, eligible_countries, ineligible_countries,
  eligible_sectors, eligible_entity_types,
  min_years_operating, max_years_operating,
  requires_kyc, requires_registration, requires_audited_financials,
  co_funding_required, co_funding_pct,
  repayment_required, equity_stake_pct, has_technical_assistance,
  application_url, deadline_type, deadline_date, avg_processing_days,
  success_rate_pct, focus_sdgs, language, status, notes
)
SELECT
  p.id, v.program_name, v.funding_type,
  v.amount_min_usd, v.amount_max_usd, v.currency, v.total_envelope_usd,
  v.eligible_regions, v.eligible_countries, v.ineligible_countries,
  v.eligible_sectors, v.eligible_entity_types,
  v.min_years_operating, v.max_years_operating,
  v.requires_kyc, v.requires_registration, v.requires_audited_financials,
  v.co_funding_required, v.co_funding_pct,
  v.repayment_required, v.equity_stake_pct, v.has_technical_assistance,
  v.application_url, v.deadline_type, v.deadline_date::DATE, v.avg_processing_days,
  v.success_rate_pct, v.focus_sdgs::INTEGER[], v.language, v.status, v.notes
FROM (VALUES

-- ── MULTILATERAL DFI PROGRAMMES ──────────────────────────

('IFC',   'IFC SME Ventures — Equity Finance', 'equity',
  500000, 15000000, 'USD', NULL,
  ARRAY['Africa','Asia','Latin America','Global'], NULL, NULL,
  ARRAY['Technology','Agriculture','Healthcare','Financial Services','Energy','Manufacturing'],
  ARRAY['startup','sme','social_enterprise'],
  2, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, 20.0, TRUE,
  'https://ifc.org/sme', 'rolling', NULL, 180,
  12.0, ARRAY[8,9,10], ARRAY['English'], 'open',
  'IFC takes minority equity stake; provides business advisory alongside capital'),

('IFC',   'IFC MSME Finance Program', 'grant',
  50000, 500000, 'USD', 500000000,
  ARRAY['Sub-Saharan Africa','South Asia'], NULL, NULL,
  ARRAY['All'],
  ARRAY['sme','cooperative','social_enterprise'],
  1, 10, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://ifc.org/msme', 'rolling', NULL, 120,
  18.0, ARRAY[8,10], ARRAY['English','French'], 'open',
  'Technical assistance grants channeled through partner banks'),

('AfDB',  'AfDB Youth Entrepreneurship & Innovation', 'grant',
  10000, 150000, 'USD', 100000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['Technology','Agriculture','Environment','Education','Healthcare'],
  ARRAY['startup','individual','social_enterprise'],
  0, 5, TRUE, FALSE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://afdb.org/youth', 'cohort', '2026-09-30', 90,
  22.0, ARRAY[1,8,9,17], ARRAY['English','French','Arabic','Portuguese'], 'open',
  'Annual cohort — up to $150K for youth-led ventures under 35'),

('AfDB',  'Affirmative Finance Action for Women in Africa (AFAWA)', 'blended_finance',
  100000, 2000000, 'USD', 3000000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['All'],
  ARRAY['sme','startup','social_enterprise'],
  0, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://afdb.org/afawa', 'rolling', NULL, 90,
  35.0, ARRAY[5,8,10], ARRAY['English','French','Arabic','Portuguese'], 'open',
  'Specifically for women-led businesses; blended debt + TA'),

('IDA',   'World Bank IDA — Micro, Small & Medium Enterprise Finance', 'grant',
  5000, 100000, 'USD', 2500000000,
  ARRAY['Sub-Saharan Africa','South Asia','Least Developed Countries'], NULL, NULL,
  ARRAY['All'],
  ARRAY['individual','startup','sme','cooperative'],
  0, NULL, TRUE, FALSE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://worldbank.org/msme', 'rolling', NULL, 150,
  15.0, ARRAY[1,2,8,10], ARRAY['English','French','Spanish','Arabic'], 'open',
  'Channeled through national government programs and MFIs'),

('GCF',   'Green Climate Fund — Private Sector Facility', 'blended_finance',
  1000000, 150000000, 'USD', 20000000000,
  ARRAY['Developing Countries','Africa','Asia','Pacific','Latin America'], NULL,
  ARRAY['USA','EU','Canada','Australia','Japan','UK'],
  ARRAY['Energy','Environment','Agriculture','Infrastructure'],
  ARRAY['startup','sme','corporate','npo'],
  2, NULL, TRUE, TRUE, TRUE, TRUE, 30.0,
  FALSE, NULL, TRUE,
  'https://greenclimate.fund/projects', 'rolling', NULL, 365,
  8.0, ARRAY[7,13,15], ARRAY['English','French','Spanish'], 'open',
  '50% co-financing required; strong climate impact evidence needed'),

('GEF',   'Global Environment Facility — SGP (Small Grants)', 'grant',
  5000, 50000, 'USD', 500000000,
  ARRAY['Africa','Asia','Latin America','Pacific'], NULL, NULL,
  ARRAY['Environment','Agriculture','Energy'],
  ARRAY['npo','cooperative','social_enterprise','individual'],
  0, NULL, FALSE, FALSE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://thegef.org/sgp', 'rolling', NULL, 90,
  40.0, ARRAY[13,14,15,6], ARRAY['English','French','Spanish','Arabic'], 'open',
  'Community-level environmental grants, avg $25K'),

('UNCDF', 'UNCDF — FinTech for Frontier Markets', 'grant',
  50000, 500000, 'USD', 50000000,
  ARRAY['Least Developed Countries','Africa','Asia'], NULL, NULL,
  ARRAY['Financial Services','Technology'],
  ARRAY['startup','sme','social_enterprise'],
  1, 7, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://uncdf.org/fintech', 'cohort', '2026-10-15', 120,
  20.0, ARRAY[1,8,10,17], ARRAY['English','French'], 'open',
  'Targets unbanked/underbanked populations; fintech only'),

('IFAD',  'IFAD Rural Finance Fund', 'grant',
  10000, 200000, 'USD', 1500000000,
  ARRAY['Africa','Asia','Latin America'], NULL, NULL,
  ARRAY['Agriculture','Food & Beverage','Environment'],
  ARRAY['cooperative','npo','sme','individual'],
  0, NULL, FALSE, FALSE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://ifad.org/projects', 'rolling', NULL, 120,
  30.0, ARRAY[1,2,12,15], ARRAY['English','French','Spanish','Arabic'], 'open',
  'Rural smallholder farmers and cooperatives; strong SSA focus'),

-- ── BILATERAL DFI PROGRAMMES ─────────────────────────────

('USAID-DIV','USAID Development Innovation Ventures (DIV)', 'grant',
  25000, 15000000, 'USD', 150000000,
  ARRAY['Global','Africa','Asia','Latin America'], NULL, ARRAY['Cuba','Iran','North Korea','Syria','Russia'],
  ARRAY['Healthcare','Agriculture','Education','Technology','Energy','Water & Sanitation'],
  ARRAY['startup','npo','sme','social_enterprise'],
  0, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://usaid.gov/div', 'rolling', NULL, 180,
  10.0, ARRAY[1,2,3,4,7,8], ARRAY['English'], 'open',
  '3-stage evidence-based model: Stage 1 ($25K–$150K), Stage 2 (up to $1.5M), Stage 3 (up to $15M)'),

('GIZ',   'GIZ — Financial System Development Programme', 'technical_assistance',
  50000, 1000000, 'USD', 200000000,
  ARRAY['Africa','Asia'], NULL, NULL,
  ARRAY['Financial Services','Technology'],
  ARRAY['sme','startup','npo','government'],
  2, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://giz.de/fsd', 'rolling', NULL, 120,
  25.0, ARRAY[8,10,17], ARRAY['English','French','German','Spanish'], 'open',
  'Technical assistance for financial sector development; pairs with loan capital'),

('AFD',   'AFD — Green & Inclusive Growth Africa', 'blended_finance',
  500000, 20000000, 'EUR', 5000000000,
  ARRAY['Africa','French-speaking Africa'], NULL, NULL,
  ARRAY['Energy','Agriculture','Infrastructure','Education','Healthcare'],
  ARRAY['sme','corporate','npo','government'],
  3, NULL, TRUE, TRUE, TRUE, TRUE, 20.0,
  FALSE, NULL, TRUE,
  'https://afd.fr/africa', 'rolling', NULL, 180,
  20.0, ARRAY[4,7,8,13], ARRAY['French','English'], 'open',
  'Strong bias toward Francophone Africa; concessional rates'),

('BII',   'British International Investment — Growth Equity', 'equity',
  1000000, 50000000, 'USD', 9000000000,
  ARRAY['Africa','South Asia','South East Asia'], NULL, NULL,
  ARRAY['Financial Services','Infrastructure','Healthcare','Technology','Energy','Agriculture'],
  ARRAY['sme','corporate','startup'],
  3, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, 25.0, TRUE,
  'https://bii.co.uk/investment', 'rolling', NULL, 270,
  15.0, ARRAY[8,9,10,13], ARRAY['English'], 'open',
  'Long-term growth equity; 7–12 year horizon; ESG mandatory'),

('DFC',   'US DFC — Small & Medium Business Finance', 'blended_finance',
  500000, 100000000, 'USD', 60000000000,
  ARRAY['Africa','Asia','Latin America','Indo-Pacific'], NULL,
  ARRAY['China','Russia','Iran','North Korea'],
  ARRAY['All'],
  ARRAY['sme','startup','corporate'],
  2, NULL, TRUE, TRUE, TRUE, TRUE, 15.0,
  FALSE, NULL, FALSE,
  'https://dfc.gov/apply', 'rolling', NULL, 180,
  30.0, ARRAY[8,9,10], ARRAY['English'], 'open',
  'Direct loans and guarantees; competes with Chinese BRI financing'),

('We-Fi', 'Women Entrepreneurs Finance Initiative', 'blended_finance',
  10000, 500000, 'USD', 350000000,
  ARRAY['Africa','Middle East','South Asia','Latin America'], NULL, NULL,
  ARRAY['All'],
  ARRAY['startup','sme','social_enterprise'],
  0, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://we-fi.org/apply', 'cohort', '2026-11-30', 120,
  28.0, ARRAY[5,8,10], ARRAY['English','French','Arabic','Spanish'], 'open',
  'Must be majority women-led or women-owned (51%+)'),

('JICA',  'JICA — Africa Business Education (ABE) Initiative', 'fellowship',
  30000, 80000, 'USD', 100000000,
  ARRAY['Sub-Saharan Africa'], NULL, NULL,
  ARRAY['Technology','Manufacturing','Agriculture','Infrastructure'],
  ARRAY['individual'],
  2, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://jica.go.jp/abe', 'cohort', '2026-09-01', 60,
  45.0, ARRAY[4,8,17], ARRAY['English','Japanese'], 'open',
  'MBA/master''s in Japan + internship; full scholarship for Africans'),

-- ── FOUNDATIONS ──────────────────────────────────────────

('Gates', 'Gates Foundation — Grand Challenges Explorations', 'grant',
  100000, 1000000, 'USD', 200000000,
  ARRAY['Global','Africa','Asia'], NULL, NULL,
  ARRAY['Healthcare','Agriculture','Technology','Education'],
  ARRAY['startup','npo','sme','individual'],
  0, NULL, FALSE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://gcgh.grandchallenges.org', 'rolling', NULL, 90,
  15.0, ARRAY[1,2,3,4], ARRAY['English'], 'open',
  '$100K initial grants; top performers get up to $1M follow-on'),

('MCF',   'Mastercard Foundation — Young Africa Works', 'grant',
  50000, 5000000, 'USD', 3000000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['Agriculture','Financial Services','Technology','Education','Manufacturing'],
  ARRAY['sme','npo','startup','social_enterprise'],
  0, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://mastercardfdn.org/youngafricaworks', 'cohort', '2026-08-31', 120,
  20.0, ARRAY[1,4,8,10], ARRAY['English','French'], 'open',
  'Targets 30M dignified jobs for youth by 2030; strong SSA focus'),

('TEF',   'Tony Elumelu Foundation Entrepreneurship Programme', 'grant',
  5000, 5000, 'USD', 100000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['All'],
  ARRAY['startup','individual'],
  0, 3, FALSE, FALSE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://tonyelumelufoundation.org/programme', 'cohort', '2027-01-31', 90,
  5.0, ARRAY[8,10], ARRAY['English','French','Portuguese','Arabic'], 'open',
  '$5K seed capital + 12-week training + mentorship; 1,000 Africans/year'),

('Ford',  'Ford Foundation — BUILD Programme', 'grant',
  100000, 3000000, 'USD', 500000000,
  ARRAY['Global','Africa'], NULL, NULL,
  ARRAY['Education','Social Impact','Environment','Human Rights'],
  ARRAY['npo','social_enterprise'],
  5, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://fordfoundation.org/build', 'rolling', NULL, 180,
  8.0, ARRAY[1,5,10,16], ARRAY['English','Spanish','Portuguese','Arabic'], 'open',
  '5-year unrestricted core support; focuses on organizational strength not just programs'),

('Omidyar','Omidyar Network — Responsible Technology Africa', 'equity',
  500000, 10000000, 'USD', 300000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['Financial Services','Technology','Education'],
  ARRAY['startup','social_enterprise'],
  1, 7, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, 15.0, TRUE,
  'https://omidyar.com/apply', 'rolling', NULL, 180,
  12.0, ARRAY[8,9,10], ARRAY['English'], 'open',
  'Impact-first equity; takes minority stake; strong Africa fintech focus'),

('Skoll', 'Skoll Foundation — Social Entrepreneurship Award', 'grant',
  1000000, 1500000, 'USD', 100000000,
  ARRAY['Global'], NULL, NULL,
  ARRAY['Social Impact','Healthcare','Environment','Education'],
  ARRAY['npo','social_enterprise'],
  5, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://skoll.org/apply', 'cohort', '2026-10-01', 180,
  3.0, ARRAY[1,3,4,10,13], ARRAY['English'], 'open',
  'Prestigious 3-year award; very competitive but no repayment'),

('Acumen','Acumen — Patient Capital Investment', 'quasi_equity',
  500000, 5000000, 'USD', 150000000,
  ARRAY['Africa','South Asia'], NULL, NULL,
  ARRAY['Healthcare','Agriculture','Energy','Education','Water & Sanitation'],
  ARRAY['startup','sme','social_enterprise'],
  1, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, 10.0, TRUE,
  'https://acumen.org/invest', 'rolling', NULL, 270,
  10.0, ARRAY[1,2,3,6,7], ARRAY['English'], 'open',
  'Patient capital — below-market returns expected; strong ESG impact'),

-- ── DEVELOPMENT BANKS ────────────────────────────────────

('Afreximbank','Afreximbank Trade Finance Guarantee', 'guarantee',
  100000, 10000000, 'USD', 2000000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['Manufacturing','Agriculture','Retail','Technology','Infrastructure'],
  ARRAY['sme','corporate'],
  2, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, NULL, FALSE,
  'https://afreximbank.com/products', 'rolling', NULL, 60,
  40.0, ARRAY[8,9,17], ARRAY['English','French','Arabic','Portuguese'], 'open',
  'Guarantees to cover 50–85% of trade finance transaction risk'),

('AGF',   'African Guarantee Fund — SME Guarantee', 'guarantee',
  10000, 2000000, 'USD', 1000000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['All'],
  ARRAY['sme','startup'],
  1, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, FALSE,
  'https://africanguaranteefund.com', 'rolling', NULL, 45,
  50.0, ARRAY[8,10], ARRAY['English','French','Portuguese','Arabic'], 'open',
  'Works through partner banks; guarantees 50% of SME loan to unlock credit'),

('IsDB',  'IsDB — Youth Entrepreneurship Support Programme', 'grant',
  10000, 100000, 'USD', 500000000,
  ARRAY['Africa','Asia','MENA'], NULL, NULL,
  ARRAY['All'],
  ARRAY['startup','individual','sme'],
  0, 5, TRUE, FALSE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://isdb.org/yesp', 'cohort', '2026-10-15', 90,
  20.0, ARRAY[1,8], ARRAY['Arabic','English','French','Urdu'], 'open',
  'Sharia-compliant; strong OIC member country focus'),

-- ── ACCELERATORS ─────────────────────────────────────────

('YC',    'Y Combinator — Startup Programme', 'equity',
  125000, 500000, 'USD', NULL,
  ARRAY['Global'], NULL, NULL,
  ARRAY['Technology','Financial Services','Healthcare','All'],
  ARRAY['startup'],
  0, 5, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, 7.0, TRUE,
  'https://ycombinator.com/apply', 'cohort', '2026-10-01', 45,
  2.0, ARRAY[8,9], ARRAY['English'], 'open',
  '$500K for 7% equity (post-money SAFE); most competitive globally'),

('Techstars','Techstars — Global Accelerator', 'equity',
  20000, 120000, 'USD', NULL,
  ARRAY['Global'], NULL, NULL,
  ARRAY['Technology','Financial Services','Healthcare','Education'],
  ARRAY['startup'],
  0, 3, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, 6.0, TRUE,
  'https://techstars.com/apply', 'cohort', NULL, 30,
  3.0, ARRAY[8,9], ARRAY['English'], 'rolling',
  '3 months intensive; $120K total investment for ~6% equity'),

('Catalyst','Catalyst Fund — Inclusive Fintech Accelerator', 'grant',
  100000, 300000, 'USD', 15000000,
  ARRAY['Africa','Asia','Latin America'], NULL, NULL,
  ARRAY['Financial Services','Technology'],
  ARRAY['startup'],
  0, 5, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://catalystfund.org/apply', 'cohort', '2026-09-01', 90,
  8.0, ARRAY[1,8,10], ARRAY['English'], 'open',
  'Non-dilutive; targets fintech for underserved; strong Africa/Asia pipeline'),

('FFA',   'Founders Factory Africa — Venture Studio', 'equity',
  100000, 500000, 'USD', 30000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['Technology','Financial Services','Healthcare','Agriculture'],
  ARRAY['startup'],
  0, 3, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, 20.0, TRUE,
  'https://foundersfactory.com/africa', 'rolling', NULL, 60,
  5.0, ARRAY[8,9,10], ARRAY['English'], 'open',
  'Venture studio model; co-builds alongside founders'),

-- ── GOVERNMENT PROGRAMMES ────────────────────────────────

('SBA',   'US SBA — Small Business Innovation Research (SBIR)', 'grant',
  50000, 2000000, 'USD', 3500000000,
  ARRAY['USA'], NULL, NULL,
  ARRAY['Technology','Healthcare','Defense','Energy','Agriculture'],
  ARRAY['startup','sme'],
  0, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://sbir.gov', 'rolling', NULL, 120,
  15.0, ARRAY[8,9], ARRAY['English'], 'open',
  'Phase I: up to $275K; Phase II: up to $1.8M; US entities only'),

('BOI',   'Bank of Industry Nigeria — SME Fund', 'blended_finance',
  5000, 500000, 'USD', 2000000000,
  ARRAY['Nigeria'], NULL, NULL,
  ARRAY['Manufacturing','Agriculture','Technology','Healthcare','Education'],
  ARRAY['sme','startup','cooperative'],
  1, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://boinigeria.com/products', 'rolling', NULL, 60,
  35.0, ARRAY[8,9], ARRAY['English'], 'open',
  'Below-market rates (5–9% p.a.); strong manufacturing bias'),

('SEFA',  'SEFA South Africa — Township & Rural Entrepreneurship', 'grant',
  5000, 100000, 'ZAR', 5000000000,
  ARRAY['South Africa'], NULL, NULL,
  ARRAY['All'],
  ARRAY['startup','individual','sme','cooperative'],
  0, 5, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://sefa.org.za/apply', 'rolling', NULL, 60,
  40.0, ARRAY[1,8,10], ARRAY['English','Zulu','Xhosa','Sotho','Afrikaans'], 'open',
  'Targets black-owned businesses in South Africa; BBBEE scoring advantage'),

-- ── IMPACT-FOCUSED ────────────────────────────────────────

('MCF',   'Mastercard Foundation — Scholars Program', 'fellowship',
  20000, 60000, 'USD', 500000000,
  ARRAY['Africa'], NULL, NULL,
  ARRAY['Education','Technology','Financial Services'],
  ARRAY['individual'],
  0, NULL, FALSE, FALSE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://mastercardfdn.org/scholars', 'cohort', '2026-11-30', 90,
  5.0, ARRAY[4,8], ARRAY['English','French'], 'open',
  'Full university scholarship for young Africans; leadership focus'),

('Kiva',  'Kiva — Zero-Interest Crowdfunded Microloans', 'grant',
  1000, 15000, 'USD', NULL,
  ARRAY['Global','Africa','Asia','Latin America'], NULL, ARRAY['Russia','North Korea','Iran'],
  ARRAY['Agriculture','Retail','Education','Healthcare','Manufacturing'],
  ARRAY['individual','sme','cooperative'],
  0, NULL, FALSE, FALSE, FALSE, FALSE, NULL,
  TRUE, NULL, FALSE,
  'https://kiva.org/apply', 'rolling', NULL, 30,
  60.0, ARRAY[1,2,8,10], ARRAY['English','Spanish','French'], 'open',
  '0% interest to borrower; crowdfunded by global lenders; 30-day raise period'),

('Grameen','Grameen Foundation — Financial Inclusion Grant', 'grant',
  5000, 100000, 'USD', 30000000,
  ARRAY['Africa','South Asia'], NULL, NULL,
  ARRAY['Financial Services','Agriculture','Healthcare'],
  ARRAY['npo','social_enterprise','cooperative'],
  2, NULL, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://grameenfoundation.org/apply', 'rolling', NULL, 90,
  15.0, ARRAY[1,2,8], ARRAY['English'], 'open',
  'Focus on last-mile financial access for rural populations'),

-- ── REGIONAL AFRICAN PROGRAMMES ──────────────────────────

('TDB',   'TDB — East Africa SME Trade Finance', 'blended_finance',
  100000, 5000000, 'USD', 500000000,
  ARRAY['East Africa','Southern Africa'],
  ARRAY['Kenya','Tanzania','Uganda','Rwanda','Zambia','Zimbabwe','Malawi','Ethiopia','DRC','Mauritius'], NULL,
  ARRAY['Manufacturing','Agriculture','Infrastructure','Technology'],
  ARRAY['sme','corporate'],
  3, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, NULL, FALSE,
  'https://tdbgroup.org/products', 'rolling', NULL, 60,
  40.0, ARRAY[8,9,17], ARRAY['English'], 'open',
  'Channeled through TDB member state banks; strong trade finance focus'),

('EBID',  'EBID — West Africa Economic Integration Fund', 'grant',
  50000, 2000000, 'USD', 200000000,
  ARRAY['West Africa'],
  ARRAY['Nigeria','Ghana','Senegal','Ivory Coast','Mali','Burkina Faso','Guinea','Benin','Togo','Niger','Sierra Leone','Liberia','Cape Verde','Gambia','Guinea-Bissau'], NULL,
  ARRAY['Infrastructure','Agriculture','Education','Healthcare'],
  ARRAY['npo','government','sme'],
  2, NULL, TRUE, TRUE, TRUE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://bidc-ebid.org', 'rolling', NULL, 120,
  20.0, ARRAY[8,9,10,17], ARRAY['French','English','Portuguese'], 'open',
  'ECOWAS member states only; francophone focus'),

-- ── CLIMATE & SUSTAINABILITY ─────────────────────────────

('GCF',   'GCF — MSME Green Finance Access', 'blended_finance',
  50000, 2000000, 'USD', 500000000,
  ARRAY['Africa','Asia','Pacific','Latin America'], NULL,
  ARRAY['USA','EU','Canada','Japan'],
  ARRAY['Energy','Agriculture','Environment','Manufacturing'],
  ARRAY['sme','startup','cooperative'],
  1, NULL, TRUE, TRUE, FALSE, TRUE, 20.0,
  FALSE, NULL, TRUE,
  'https://greenclimate.fund/msme', 'rolling', NULL, 150,
  15.0, ARRAY[7,12,13,15], ARRAY['English','French','Spanish'], 'open',
  'Specifically for climate-aligned SMEs; channeled through accredited entities'),

('GEF',   'GEF — Circular Economy Innovation Challenge', 'prize',
  10000, 200000, 'USD', 20000000,
  ARRAY['Global','Africa','Asia'], NULL, NULL,
  ARRAY['Environment','Manufacturing','Agriculture'],
  ARRAY['startup','sme','npo','social_enterprise','individual'],
  0, NULL, FALSE, FALSE, FALSE, FALSE, NULL,
  FALSE, NULL, FALSE,
  'https://thegef.org/circular', 'cohort', '2026-09-15', 60,
  5.0, ARRAY[12,13,15,17], ARRAY['English'], 'open',
  'Innovation prize; no equity taken; judged by circular economy impact'),

-- ── ISLAMIC FINANCE ──────────────────────────────────────

('IsDB',  'IsDB — IsDB Transform Fund (SME Grant-Loan)', 'blended_finance',
  25000, 1000000, 'USD', 2000000000,
  ARRAY['Africa','Asia','MENA'],
  NULL, NULL,
  ARRAY['Technology','Agriculture','Healthcare','Education','Manufacturing'],
  ARRAY['startup','sme','social_enterprise'],
  0, 7, TRUE, TRUE, FALSE, FALSE, NULL,
  FALSE, NULL, TRUE,
  'https://isdb.org/transform', 'cohort', '2026-11-01', 90,
  18.0, ARRAY[1,8,9,10], ARRAY['Arabic','English','French','Urdu'], 'open',
  'Sharia-compliant blended finance; 57 OIC member countries eligible')

) AS v (
  short_name, program_name, funding_type,
  amount_min_usd, amount_max_usd, currency, total_envelope_usd,
  eligible_regions, eligible_countries, ineligible_countries,
  eligible_sectors, eligible_entity_types,
  min_years_operating, max_years_operating,
  requires_kyc, requires_registration, requires_audited_financials,
  co_funding_required, co_funding_pct,
  repayment_required, equity_stake_pct, has_technical_assistance,
  application_url, deadline_type, deadline_date, avg_processing_days,
  success_rate_pct, focus_sdgs, language, status, notes
)
JOIN p ON p.short_name = v.short_name;
