-- ============================================================
-- SEED: GLOBAL LOAN PRODUCTS
-- 35 real loan products — all variables for matchmaking
-- From microfinance to sovereign; fixed/floating; all regions
-- ============================================================

WITH p AS (SELECT id, short_name FROM public.capital_providers)
INSERT INTO public.capital_loans (
  provider_id, product_name, loan_type,
  rate_structure, base_rate_benchmark, base_rate_value, spread_min_pct, spread_max_pct,
  total_rate_min_pct, total_rate_max_pct, currency,
  amount_min_usd, amount_max_usd,
  tenor_min_months, tenor_max_months, grace_period_months,
  ltv_max_pct, collateral_required, collateral_types, guarantor_required,
  credit_score_min,
  eligible_regions, eligible_countries, eligible_sectors, eligible_entity_types,
  min_annual_revenue_usd, min_years_in_business,
  requires_kyc, requires_audited_financials,
  origination_fee_pct, annual_fee_pct, prepayment_penalty, prepayment_penalty_pct,
  application_url, avg_approval_days, status, notes
)
SELECT
  p.id, v.product_name, v.loan_type,
  v.rate_structure, v.base_rate_benchmark, v.base_rate_value, v.spread_min_pct, v.spread_max_pct,
  v.total_rate_min_pct, v.total_rate_max_pct, v.currency,
  v.amount_min_usd, v.amount_max_usd,
  v.tenor_min_months, v.tenor_max_months, v.grace_period_months,
  v.ltv_max_pct::NUMERIC, v.collateral_required, v.collateral_types, v.guarantor_required,
  v.credit_score_min::INTEGER,
  v.eligible_regions, v.eligible_countries, v.eligible_sectors, v.eligible_entity_types,
  v.min_annual_revenue_usd::NUMERIC, v.min_years_in_business,
  v.requires_kyc, v.requires_audited_financials,
  v.origination_fee_pct::NUMERIC, v.annual_fee_pct::NUMERIC, v.prepayment_penalty, v.prepayment_penalty_pct::NUMERIC,
  v.application_url, v.avg_approval_days, v.status, v.notes
FROM (VALUES

-- ── MULTILATERAL / DFI LOANS ─────────────────────────────

('IFC', 'IFC Direct Loan — SME Finance', 'term_loan',
  'floating', 'SOFR_6M', 4.48, 3.0, 6.0,
  7.5, 10.5, 'USD',
  1000000, 100000000,
  36, 180, 12,
  70.0, TRUE, ARRAY['real_estate','equipment','receivables','guarantee'], FALSE,
  NULL,
  ARRAY['Africa','Asia','Latin America','Global'], NULL, ARRAY['All'], ARRAY['sme','corporate'],
  1000000, 3, TRUE, TRUE,
  1.0, 0.5, FALSE, NULL,
  'https://ifc.org/loans', 180, 'active',
  'IFC direct loans start at $1M; smaller amounts through financial intermediaries'),

('IFC', 'IFC MSME Loan — Via Partner Banks', 'term_loan',
  'floating', 'SOFR_3M', 4.42, 4.0, 8.0,
  8.5, 12.5, 'USD',
  10000, 500000,
  12, 84, 3,
  60.0, TRUE, ARRAY['equipment','invoice','guarantee','real_estate'], FALSE,
  NULL,
  ARRAY['Sub-Saharan Africa','South Asia'], NULL, ARRAY['All'], ARRAY['sme','startup','cooperative'],
  50000, 1, TRUE, FALSE,
  2.0, 1.0, FALSE, NULL,
  'https://ifc.org/msme', 60, 'active',
  'On-lent through IFC partner banks; rates vary by country and bank'),

('AfDB', 'AfDB Private Sector Development Loan', 'term_loan',
  'floating', 'SOFR_6M', 4.48, 2.5, 5.0,
  7.0, 9.5, 'USD',
  2000000, 150000000,
  36, 240, 24,
  75.0, TRUE, ARRAY['real_estate','equipment','government_guarantee'], FALSE,
  NULL,
  ARRAY['Africa'], NULL, ARRAY['Infrastructure','Energy','Manufacturing','Agriculture'], ARRAY['corporate','sme'],
  2000000, 5, TRUE, TRUE,
  1.5, 0.5, FALSE, NULL,
  'https://afdb.org/private-sector', 270, 'active',
  'Long-tenor infrastructure loans; grace period standard 2 years'),

('IDA', 'World Bank IDA — Concessional Development Credit', 'concessional',
  'fixed', 'FIXED', 0.0, 0.75, 1.25,
  0.75, 1.25, 'USD',
  500000, 500000000,
  120, 360, 60,
  NULL, FALSE, ARRAY['none'], FALSE,
  NULL,
  ARRAY['Sub-Saharan Africa','Least Developed Countries','South Asia'], NULL, ARRAY['All'], ARRAY['government','npo'],
  NULL, 0, TRUE, TRUE,
  0.25, 0.0, FALSE, NULL,
  'https://worldbank.org/ida', 365, 'active',
  '0.75–1.25% service charge only; for IDA-eligible governments and public entities'),

('EBRD', 'EBRD Green Economy Financing Facility', 'green_loan',
  'floating', 'EURIBOR_3M', 2.35, 2.5, 5.0,
  4.85, 7.35, 'EUR',
  200000, 10000000,
  36, 120, 12,
  70.0, TRUE, ARRAY['equipment','real_estate','energy_assets'], FALSE,
  NULL,
  ARRAY['Africa','Central Asia','Europe'], NULL, ARRAY['Energy','Environment','Manufacturing','Agriculture'], ARRAY['sme','corporate'],
  200000, 2, TRUE, TRUE,
  1.0, 0.5, FALSE, NULL,
  'https://ebrd.com/geff', 90, 'active',
  'Incentive grant of 10–20% on top of loan for qualifying green investments'),

('EIB', 'EIB Africa Infrastructure Finance Facility', 'project_finance',
  'fixed', 'FIXED', 0.0, 3.0, 6.0,
  3.0, 6.0, 'EUR',
  5000000, 200000000,
  60, 300, 36,
  80.0, TRUE, ARRAY['infrastructure_assets','government_guarantee','revenue_stream'], FALSE,
  NULL,
  ARRAY['Africa'], NULL, ARRAY['Infrastructure','Energy','Transport','Water & Sanitation'], ARRAY['government','corporate'],
  NULL, 5, TRUE, TRUE,
  1.0, 0.25, FALSE, NULL,
  'https://eib.org/africa', 365, 'active',
  'Long-tenor project finance; blended with EU grant component when possible'),

-- ── DEVELOPMENT BANK LOANS ───────────────────────────────

('Afreximbank', 'Afreximbank Trade Finance Facility', 'trade_finance',
  'floating', 'SOFR_3M', 4.42, 3.5, 7.0,
  8.0, 11.5, 'USD',
  100000, 50000000,
  3, 60, 0,
  NULL, FALSE, ARRAY['invoice','letter_of_credit','guarantee'], TRUE,
  NULL,
  ARRAY['Africa'], NULL, ARRAY['Manufacturing','Agriculture','Retail','Technology'], ARRAY['sme','corporate'],
  500000, 2, TRUE, TRUE,
  1.5, 0.0, FALSE, NULL,
  'https://afreximbank.com/trade', 45, 'active',
  'Import/export financing; LC confirmation; factoring available'),

('Afreximbank', 'Afreximbank MANSA SME Loan', 'term_loan',
  'floating', 'SOFR_6M', 4.48, 4.0, 7.5,
  8.5, 12.0, 'USD',
  50000, 2000000,
  12, 84, 3,
  60.0, TRUE, ARRAY['real_estate','equipment','invoice','guarantee'], FALSE,
  NULL,
  ARRAY['Africa'], NULL, ARRAY['Manufacturing','Agriculture','Technology','Healthcare'], ARRAY['sme','startup'],
  100000, 1, TRUE, FALSE,
  2.0, 0.5, FALSE, NULL,
  'https://afreximbank.com/mansa', 60, 'active',
  'MANSA KYC platform verified; Africa SME focus'),

('TDB', 'TDB SME Development Finance Loan', 'term_loan',
  'floating', 'SOFR_6M', 4.48, 3.5, 6.5,
  8.0, 11.0, 'USD',
  100000, 5000000,
  12, 120, 6,
  65.0, TRUE, ARRAY['real_estate','equipment','receivables'], FALSE,
  NULL,
  ARRAY['East Africa','Southern Africa'],
  ARRAY['Kenya','Tanzania','Uganda','Rwanda','Zambia','Zimbabwe','Malawi','Ethiopia','DRC','Mauritius'], ARRAY['All'], ARRAY['sme','corporate'],
  200000, 2, TRUE, TRUE,
  1.5, 0.25, FALSE, NULL,
  'https://tdbgroup.org/sme', 60, 'active',
  'TDB member countries only; strong trade and project finance'),

('IsDB', 'Islamic Development Bank — Murabaha SME Finance', 'islamic_murabaha',
  'fixed', 'SAIBOR_3M', 5.20, 2.0, 4.5,
  7.2, 9.7, 'USD',
  50000, 5000000,
  12, 120, 6,
  70.0, TRUE, ARRAY['equipment','real_estate','inventory'], FALSE,
  NULL,
  ARRAY['Africa','Asia','MENA'], NULL, ARRAY['All'], ARRAY['sme','startup','cooperative'],
  100000, 1, TRUE, TRUE,
  1.5, 0.0, FALSE, NULL,
  'https://isdb.org/murabaha', 90, 'active',
  'Sharia-compliant cost-plus financing; no interest — profit-sharing model'),

('IsDB', 'Islamic Development Bank — Ijara Leasing', 'islamic_ijara',
  'fixed', 'SAIBOR_3M', 5.20, 2.5, 5.0,
  7.7, 10.2, 'USD',
  50000, 10000000,
  24, 120, 0,
  80.0, TRUE, ARRAY['equipment','vehicles','machinery'], FALSE,
  NULL,
  ARRAY['Africa','Asia','MENA'], NULL, ARRAY['Manufacturing','Agriculture','Healthcare','Transport'], ARRAY['sme','corporate'],
  100000, 2, TRUE, TRUE,
  1.0, 0.5, FALSE, NULL,
  'https://isdb.org/ijara', 90, 'active',
  'Asset-backed leasing; asset stays with IsDB until end of contract'),

-- ── GOVERNMENT & NATIONAL PROGRAMMES ────────────────────

('SBA', 'US SBA 7(a) Small Business Loan', 'term_loan',
  'floating', 'US_PRIME', 7.50, 2.25, 4.75,
  9.75, 12.25, 'USD',
  5000, 5000000,
  12, 300, 0,
  85.0, TRUE, ARRAY['real_estate','equipment','receivables','business_assets'], FALSE,
  620,
  ARRAY['USA'], NULL, ARRAY['All'], ARRAY['startup','sme'],
  NULL, 0, TRUE, FALSE,
  3.0, 0.0, FALSE, NULL,
  'https://sba.gov/7a', 30, 'active',
  'SBA guarantees 75–85% of loan; most flexible US govt SME product'),

('SBA', 'US SBA 504 Equipment & Real Estate Loan', 'term_loan',
  'fixed', 'US_T10Y', 4.52, 2.0, 3.0,
  6.5, 7.5, 'USD',
  125000, 20000000,
  120, 300, 0,
  90.0, TRUE, ARRAY['real_estate','equipment'], FALSE,
  680,
  ARRAY['USA'], NULL, ARRAY['Manufacturing','Agriculture','Healthcare','Retail'], ARRAY['sme'],
  NULL, 2, TRUE, FALSE,
  1.5, 0.0, FALSE, NULL,
  'https://sba.gov/504', 45, 'active',
  'Fixed rate; only for fixed assets (real estate, heavy equipment); CDC partnership'),

('BOI', 'Bank of Industry Nigeria — SME Loan', 'term_loan',
  'fixed', 'FIXED', 0.0, 0.0, 0.0,
  5.0, 9.0, 'NGN',
  5000, 200000,
  12, 120, 6,
  60.0, TRUE, ARRAY['real_estate','equipment','guarantee'], FALSE,
  NULL,
  ARRAY['Nigeria'], NULL, ARRAY['Manufacturing','Agriculture','Healthcare','Technology'], ARRAY['sme','startup','cooperative'],
  20000, 1, TRUE, FALSE,
  1.0, 0.5, FALSE, NULL,
  'https://boinigeria.com/sme', 60, 'active',
  'NGN denominated; 5–9% fixed p.a.; government-subsidized'),

('BOI', 'Bank of Industry Nigeria — Cottage Industry Microloan', 'microfinance',
  'fixed', 'FIXED', 0.0, 0.0, 0.0,
  5.0, 5.0, 'NGN',
  500, 5000,
  6, 36, 0,
  NULL, FALSE, ARRAY['none','group_guarantee'], TRUE,
  NULL,
  ARRAY['Nigeria'], NULL, ARRAY['Manufacturing','Agriculture','Retail','Food & Beverage'], ARRAY['individual','cooperative'],
  NULL, 0, TRUE, FALSE,
  0.5, 0.0, FALSE, NULL,
  'https://boinigeria.com/cottage', 14, 'active',
  'Smallest loan product; group lending model; for informal sector'),

-- ── COMMERCIAL BANK PRODUCTS ─────────────────────────────

('Stanbic', 'Stanbic Africa Business Loan', 'term_loan',
  'floating', 'SOFR_3M', 4.42, 5.0, 9.0,
  9.5, 13.5, 'USD',
  50000, 5000000,
  12, 84, 3,
  65.0, TRUE, ARRAY['real_estate','equipment','receivables'], FALSE,
  NULL,
  ARRAY['Africa'], NULL, ARRAY['All'], ARRAY['sme','corporate'],
  250000, 2, TRUE, TRUE,
  2.0, 1.0, FALSE, NULL,
  'https://stanbic.com/business-loans', 30, 'active',
  'Available across 20+ African markets; fastest approval in Stanbic network'),

('Ecobank', 'Ecobank Ellevate — Women SME Loan', 'term_loan',
  'floating', 'SOFR_3M', 4.42, 4.0, 7.5,
  8.5, 12.0, 'USD',
  5000, 200000,
  6, 60, 3,
  60.0, TRUE, ARRAY['equipment','invoice','guarantee'], FALSE,
  NULL,
  ARRAY['Africa'], NULL, ARRAY['Retail','Agriculture','Manufacturing','Technology'], ARRAY['sme','startup'],
  20000, 1, TRUE, FALSE,
  2.5, 0.5, FALSE, NULL,
  'https://ecobank.com/ellevate', 21, 'active',
  'Women-only product; 35 African countries; lower rate than standard SME'),

('Ecobank', 'Ecobank Trade Finance — Import/Export Loan', 'trade_finance',
  'floating', 'SOFR_1M', 4.35, 3.5, 6.5,
  8.0, 11.0, 'USD',
  10000, 1000000,
  1, 24, 0,
  NULL, FALSE, ARRAY['letter_of_credit','invoice','guarantee'], TRUE,
  NULL,
  ARRAY['Africa'], NULL, ARRAY['Manufacturing','Agriculture','Retail','Technology'], ARRAY['sme','corporate'],
  100000, 2, TRUE, FALSE,
  1.5, 0.0, FALSE, NULL,
  'https://ecobank.com/trade', 14, 'active',
  'LC confirmation, bills for collection, supply chain finance'),

('Equity', 'Equity Bank Kenya — Micro Business Loan', 'microfinance',
  'fixed', 'FIXED', 0.0, 0.0, 0.0,
  13.0, 18.0, 'KES',
  500, 50000,
  3, 36, 0,
  NULL, FALSE, ARRAY['group_guarantee','salary_deduction','equipment'], FALSE,
  NULL,
  ARRAY['East Africa'], ARRAY['Kenya','Uganda','Tanzania','DRC','Rwanda'], ARRAY['Agriculture','Retail','Food & Beverage'], ARRAY['individual','cooperative'],
  NULL, 0, TRUE, FALSE,
  3.0, 0.0, FALSE, NULL,
  'https://equitygroupholdings.com/micro', 7, 'active',
  'Mobile-disbursed via Equity Mobile app; flexible repayment'),

('Equity', 'Equity Bank — SME Term Loan', 'term_loan',
  'floating', 'CBK_CBR', 10.00, 4.0, 7.0,
  14.0, 17.0, 'KES',
  50000, 5000000,
  12, 120, 6,
  70.0, TRUE, ARRAY['real_estate','equipment','title_deed'], FALSE,
  NULL,
  ARRAY['East Africa'], ARRAY['Kenya','Uganda','Tanzania'], ARRAY['All'], ARRAY['sme','startup'],
  100000, 1, TRUE, FALSE,
  2.0, 0.5, FALSE, NULL,
  'https://equitygroupholdings.com/sme', 21, 'active',
  'KES denominated; CBR-linked floating rate'),

-- ── MICROFINANCE ─────────────────────────────────────────

('Kiva', 'Kiva Direct — 0% Crowdfunded Microloan', 'microfinance',
  'fixed', 'FIXED', 0.0, 0.0, 0.0,
  0.0, 0.0, 'USD',
  1000, 15000,
  6, 36, 0,
  NULL, FALSE, ARRAY['none','social_collateral'], TRUE,
  NULL,
  ARRAY['Global','Africa','Asia','Latin America'], NULL, ARRAY['Agriculture','Retail','Healthcare','Education','Manufacturing'], ARRAY['individual','cooperative','sme'],
  NULL, 0, FALSE, FALSE,
  0.0, 0.0, FALSE, NULL,
  'https://kiva.org/borrow', 30, 'active',
  '0% interest; crowdfunded; 30-day fundraising window; Kiva Field Partner co-guarantees'),

('FINCA', 'FINCA Africa — Solidarity Group Microloan', 'microfinance',
  'fixed', 'FIXED', 0.0, 0.0, 0.0,
  24.0, 48.0, 'USD',
  200, 5000,
  3, 18, 0,
  NULL, FALSE, ARRAY['group_guarantee'], TRUE,
  NULL,
  ARRAY['Africa'], ARRAY['DRC','Tanzania','Uganda','Zambia','Malawi','Nigeria'], ARRAY['Agriculture','Retail','Food & Beverage'], ARRAY['individual','cooperative'],
  NULL, 0, FALSE, FALSE,
  3.0, 0.0, FALSE, NULL,
  'https://finca.org/apply', 14, 'active',
  'Group lending 5–10 members; weekly repayment; last-mile rural reach'),

('OI', 'Opportunity International — Enterprise Microloan', 'microfinance',
  'floating', 'FIXED', 0.0, 0.0, 0.0,
  18.0, 36.0, 'USD',
  300, 10000,
  6, 24, 0,
  NULL, FALSE, ARRAY['social_collateral','equipment'], FALSE,
  NULL,
  ARRAY['Africa','Asia'], ARRAY['Ghana','Rwanda','Malawi','Mozambique','Tanzania'], ARRAY['Agriculture','Retail','Manufacturing'], ARRAY['individual','cooperative'],
  NULL, 0, FALSE, FALSE,
  2.0, 0.0, FALSE, NULL,
  'https://opportunity.org/loans', 21, 'active',
  'Paired with financial literacy training; strong women client base'),

-- ── SPECIALIZED PRODUCTS ─────────────────────────────────

('DFC', 'US DFC — Direct Loan for Infrastructure', 'project_finance',
  'fixed', 'US_T10Y', 4.52, 1.5, 4.0,
  6.0, 8.5, 'USD',
  1000000, 1000000000,
  60, 300, 36,
  80.0, TRUE, ARRAY['infrastructure_assets','revenue_stream','government_guarantee'], FALSE,
  NULL,
  ARRAY['Africa','Asia','Latin America','Indo-Pacific'], NULL, ARRAY['Infrastructure','Energy','Healthcare','Technology'], ARRAY['corporate','sme','government'],
  NULL, 5, TRUE, TRUE,
  0.5, 0.25, FALSE, NULL,
  'https://dfc.gov/direct-loans', 270, 'active',
  'Competes directly with Chinese BRI; no OPIC restrictions'),

('EIB', 'EIB Global — SME Access to Finance', 'term_loan',
  'floating', 'EURIBOR_6M', 2.40, 2.0, 5.0,
  4.4, 7.4, 'EUR',
  25000, 7500000,
  12, 120, 6,
  70.0, TRUE, ARRAY['real_estate','equipment','guarantee'], FALSE,
  NULL,
  ARRAY['Africa','Asia'], NULL, ARRAY['All'], ARRAY['sme','startup'],
  50000, 1, TRUE, FALSE,
  1.0, 0.5, FALSE, NULL,
  'https://eib.org/sme-global', 90, 'active',
  'Channeled through local partner banks; EUR or local currency'),

('BII', 'BII Growth Capital Loan', 'term_loan',
  'floating', 'SOFR_6M', 4.48, 4.0, 8.0,
  8.5, 12.5, 'USD',
  500000, 30000000,
  36, 180, 12,
  70.0, TRUE, ARRAY['real_estate','equipment','receivables','business_assets'], FALSE,
  NULL,
  ARRAY['Africa','South Asia'], NULL, ARRAY['Financial Services','Healthcare','Infrastructure','Agriculture','Technology'], ARRAY['sme','corporate'],
  500000, 3, TRUE, TRUE,
  2.0, 0.5, FALSE, NULL,
  'https://bii.co.uk/loans', 180, 'active',
  'ESG requirements mandatory; 7–12 year investment horizon'),

('EBID', 'EBID West Africa SME Credit Line', 'revolving_credit',
  'floating', 'EURIBOR_6M', 2.40, 3.5, 7.0,
  5.9, 9.4, 'USD',
  50000, 2000000,
  12, 60, 0,
  60.0, TRUE, ARRAY['invoice','receivables','equipment'], FALSE,
  NULL,
  ARRAY['West Africa'], ARRAY['Nigeria','Ghana','Senegal','Ivory Coast','Mali','Burkina Faso','Guinea','Benin','Togo'], ARRAY['Manufacturing','Agriculture','Retail','Technology'], ARRAY['sme','startup'],
  50000, 1, TRUE, FALSE,
  2.5, 0.5, FALSE, NULL,
  'https://bidc-ebid.org/sme', 60, 'active',
  'ECOWAS member states; revolving facility for working capital'),

('AFD', 'AFD ProParco — SME Growth Loan (French Africa)', 'term_loan',
  'floating', 'EURIBOR_6M', 2.40, 3.0, 6.0,
  5.4, 8.4, 'EUR',
  200000, 10000000,
  24, 120, 12,
  70.0, TRUE, ARRAY['real_estate','equipment','guarantee'], FALSE,
  NULL,
  ARRAY['French-speaking Africa','Africa'], NULL, ARRAY['All'], ARRAY['sme','corporate'],
  200000, 3, TRUE, TRUE,
  1.5, 0.25, FALSE, NULL,
  'https://proparco.fr/sme', 90, 'active',
  'ProParco is AFD''s private sector arm; strong Francophone Africa bias'),

('MCF', 'Mastercard Foundation — Young Africa Works Loan', 'blended',
  'fixed', 'FIXED', 0.0, 0.0, 0.0,
  6.0, 12.0, 'USD',
  5000, 200000,
  6, 60, 3,
  NULL, FALSE, ARRAY['social_collateral','guarantee'], FALSE,
  NULL,
  ARRAY['Africa'], NULL, ARRAY['Agriculture','Technology','Manufacturing','Retail','Education'], ARRAY['startup','individual','cooperative'],
  NULL, 0, TRUE, FALSE,
  1.0, 0.0, FALSE, NULL,
  'https://mastercardfdn.org/loans', 30, 'active',
  'Blended with grant component; channeled through local MFI partners')

) AS v (
  short_name, product_name, loan_type,
  rate_structure, base_rate_benchmark, base_rate_value, spread_min_pct, spread_max_pct,
  total_rate_min_pct, total_rate_max_pct, currency,
  amount_min_usd, amount_max_usd,
  tenor_min_months, tenor_max_months, grace_period_months,
  ltv_max_pct, collateral_required, collateral_types, guarantor_required,
  credit_score_min,
  eligible_regions, eligible_countries, eligible_sectors, eligible_entity_types,
  min_annual_revenue_usd, min_years_in_business,
  requires_kyc, requires_audited_financials,
  origination_fee_pct, annual_fee_pct, prepayment_penalty, prepayment_penalty_pct,
  application_url, avg_approval_days, status, notes
)
JOIN p ON p.short_name = v.short_name;
